# Generated by Django 3.2.16 on 2022-12-13 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0004_auto_20221213_1223'),
        ('posts', '0004_imagepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagePost',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='TextPost',
        ),
    ]
