# Generated by Django 3.2.16 on 2022-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-created_at']},
        ),
    ]
